## CharRNN - Harry Potter

Character wise RNN to generate new text based on Harry Potter Books.

In [2]:
import tensorflow as tf
import numpy as np
import time
from collections import Counter

Load the text file and convert it into integers using dictionaries to convert the characters to and from integers. We will only use the 1st book Harry Potter and Sorcerer's Stone.

In [3]:
text = open('HPBook1.txt', 'r')
text = text.read()
print('Some sample text from the book -->')
text[:1000]

Some sample text from the book -->


"Harry Potter and the Sorcerer's Stone \n\nCHAPTER ONE \n\nTHE BOY WHO LIVED \n\nMr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense. \n\nMr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere. \n\nThe Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn't think they could bear it if anyone found out about 

#### Some text analysis

In [4]:
total_words = len(text.split())
total_characters = len(text)
unique_words = len(set(text.split()))
unique_characters = len(set(text))

print ("Total words in book :", total_words)
print ("Total characters in book :", total_characters)
print ("Unique words in book :", unique_words)
print ("Unique characters in book :", unique_characters)

Total words in book : 78449
Total characters in book : 442744
Unique words in book : 11897
Unique characters in book : 80


In [5]:
paragraphs = text.split('\n\n')
print ("Total Paragraphs :", len(paragraphs))

Total Paragraphs : 3033


In [6]:
most_words = Counter()
for i in range(len(paragraphs)):
    for x in paragraphs[i]:
        most_words[x] +=1

In [7]:
most_words.most_common()

[(' ', 78449),
 ('e', 39628),
 ('t', 27993),
 ('a', 25887),
 ('o', 25809),
 ('n', 21337),
 ('r', 20990),
 ('h', 19535),
 ('i', 19422),
 ('s', 18870),
 ('d', 15932),
 ('l', 14385),
 ('u', 9562),
 ('y', 8293),
 ('g', 8127),
 ('w', 7744),
 ('m', 6729),
 ('f', 6431),
 ('c', 6403),
 ('.', 6136),
 (',', 5658),
 ('b', 4980),
 ('p', 4909),
 ('"', 4747),
 ('k', 3930),
 ("'", 3141),
 ('H', 2996),
 ('v', 2716),
 ('-', 1986),
 ('I', 1393),
 ('T', 1055),
 ('S', 844),
 ('?', 754),
 ('A', 703),
 ('D', 685),
 ('M', 665),
 ('R', 660),
 ('W', 653),
 ('P', 639),
 ('G', 492),
 ('N', 488),
 ('!', 474),
 ('F', 426),
 ('x', 381),
 ('B', 348),
 ('O', 332),
 ('Y', 326),
 ('j', 319),
 ('C', 293),
 ('E', 287),
 ('z', 259),
 ('q', 217),
 ('L', 209),
 ('Q', 203),
 ('U', 193),
 ('V', 192),
 (';', 135),
 ('K', 79),
 (':', 69),
 ('J', 51),
 (')', 33),
 ('(', 30),
 ('“', 11),
 ('1', 11),
 ('3', 8),
 ('4', 6),
 ('Z', 5),
 ('0', 5),
 ('7', 4),
 ('9', 4),
 ('2', 3),
 ('X', 2),
 ('5', 2),
 ('*', 2),
 ('–', 1),
 ('~', 1),


In [13]:
set(text)

{'\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '\\',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '~',
 '–',
 '“'}

In [8]:
vocab = sorted(set(text))
vocab_to_int = {c : i for i,c in enumerate(vocab)}
#int_to_vocab = {i : c for i,c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
embeddings = np.array([vocab_to_int[i] for i in text], dtype=np.int32)

In [12]:
vocab_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '?': 23,
 'A': 24,
 'B': 25,
 'C': 26,
 'D': 27,
 'E': 28,
 'F': 29,
 'G': 30,
 'H': 31,
 'I': 32,
 'J': 33,
 'K': 34,
 'L': 35,
 'M': 36,
 'N': 37,
 'O': 38,
 'P': 39,
 'Q': 40,
 'R': 41,
 'S': 42,
 'T': 43,
 'U': 44,
 'V': 45,
 'W': 46,
 'X': 47,
 'Y': 48,
 'Z': 49,
 '\\': 50,
 'a': 51,
 'b': 52,
 'c': 53,
 'd': 54,
 'e': 55,
 'f': 56,
 'g': 57,
 'h': 58,
 'i': 59,
 'j': 60,
 'k': 61,
 'l': 62,
 'm': 63,
 'n': 64,
 'o': 65,
 'p': 66,
 'q': 67,
 'r': 68,
 's': 69,
 't': 70,
 'u': 71,
 'v': 72,
 'w': 73,
 'x': 74,
 'y': 75,
 'z': 76,
 '~': 77,
 '–': 78,
 '“': 79}

In [10]:
print ("Examples encodings (inputs to our NN) -->>")
print (text[:120])
print (embeddings[:120])

Examples encodings (inputs to our NN) -->>
Harry Potter and the Sorcerer's Stone 

CHAPTER ONE 

THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet D
[31 51 68 68 75  1 39 65 70 70 55 68  1 51 64 54  1 70 58 55  1 42 65 68 53
 55 68 55 68  4 69  1 42 70 65 64 55  1  0  0 26 31 24 39 43 28 41  1 38 37
 28  1  0  0 43 31 28  1 25 38 48  1 46 31 38  1 35 32 45 28 27  1  0  0 36
 68 10  1 51 64 54  1 36 68 69 10  1 27 71 68 69 62 55 75  8  1 65 56  1 64
 71 63 52 55 68  1 56 65 71 68  8  1 39 68 59 72 55 70  1 27]


Since we are working with individual characters, it's a classification problem in which we are trying to predict the next character from the previous text. Here's how many 'classes' our network has to pick from.

### Building the Model

Defining placeholders for inputs, targets, learning rate and dropout rate

In [49]:
def placeholders(batch_size, step_size):
    inputs = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='inputs')
    targets = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='targets')
    #lr = tf.placeholder(tf.float32, name='learning_rate')
    keep_prob = tf.placeholder(tf.float32, name= 'prob')
    
    return inputs, targets, keep_prob

Creating LSTM cells for our RNN

In [11]:
def lstms(lstm_size, layers, batch_size, keep_prob):
    
    def build_cell(lstm_size, keep_prob):
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(layers)])
    state = cell.zero_state(batch_size, tf.float32)
    
    return cell, state

Output from RNN

In [41]:
def rnn_output(lstm_output, input_size, output_size):
    sequence = tf.concat(lstm_output, axis=1)
    x = tf.reshape(sequence, [-1, input_size])
    
    with tf.variable_scope('softmax'):
        weights = tf.Variable(tf.truncated_normal(shape=(input_size, output_size), stddev=0.1))
        bias = tf.Variable(tf.zeros(output_size))
        
    logits = tf.matmul(x, weights) + bias
    predictions = tf.nn.softmax(logits, name='predictions')                          
    
    return predictions, logits

Calcualting loss for the network

In [42]:
def losses(logits, y, lstm_size, num_classes):
    labels = tf.reshape(tf.one_hot(y, num_classes), logits.get_shape())
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
    
    return loss

Defining Hyperparameters

In [43]:
batch_size = 64
num_steps = 50        
lstm_size = 128 
num_layers = 2         
learning_rate = 0.001  
prob = 0.5 
grad_clip = 5
num_classes = len(vocab)

Generating batches to feed into NN

In [44]:
def generate_batches(inputs, batch_size, num_steps):
    char_batch = batch_size * num_steps
    num_batches = len(inputs)//char_batch
    
    idx = char_batch * num_batches 
    inputs = inputs[:idx]
    inputs = inputs.reshape((batch_size, -1))
    
    for i in range(0, inputs.shape[1], num_steps):
        x = inputs[:, i : i+num_steps]
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        
        yield x, y

In [45]:
batches = generate_batches(embeddings, 10, 50)
x, y = next(batches)

In [46]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 51 68 68 75  1 39 65 70 70]
 [ 1 69 66 65 61 55  1 51 52 65]
 [70 69  1 52 55 51 61 10  1  0]
 [64 65 69 55 10  1  0  0  3 48]
 [70 58 55 59 68  1 56 51 53 55]
 [56 65 75 69  1 69 64 55 55 68]
 [64 70  1 57 51 59 64 69  1 70]
 [ 1 51 64 65 70 58 55 68  1 68]
 [51 68 54  1 58 59 63  1 51 64]
 [65 62 65 57 75  8  1 31 55 68]]

y
 [[51 68 68 75  1 39 65 70 70 55]
 [69 66 65 61 55  1 51 52 65 71]
 [69  1 52 55 51 61 10  1  0  0]
 [65 69 55 10  1  0  0  3 48 55]
 [58 55 59 68  1 56 51 53 55 69]
 [65 75 69  1 69 64 55 55 68 59]
 [70  1 57 51 59 64 69  1 70 58]
 [51 64 65 70 58 55 68  1 68 55]
 [68 54  1 58 59 63  1 51 64 54]
 [62 65 57 75  8  1 31 55 68 63]]


Optimizer and fixing exploding gradient problem by clipping beyond a threshold

In [50]:
def cal_optimizer(loss, learning_rate, clipping):
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), clipping)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

In [ ]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = placeholders(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = lstms(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = rnn_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = losses(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = optimizer(self.loss, learning_rate, grad_clip)

During Training

In [51]:
tf.reset_default_graph()

## Getting input tensors
inputs, targets, keep_prob = placeholders(batch_size, num_steps)

## Creating LSTM Cell
cell, initial_state = lstms(lstm_size, num_layers, batch_size, keep_prob)

## One hot encode inputs to run the data through RNN layers
one_hot_inputs = tf.one_hot(inputs, num_classes)

## Collect outputs
outputs, state = tf.nn.dynamic_rnn(cell, one_hot_inputs, initial_state = initial_state)
final_state = state

## Predictions and Logits
predictions, logits = rnn_output(outputs, lstm_size, num_classes)

## Getting losses and optimizer(ADAM)
loss = losses(logits, targets, lstm_size, num_classes)
optimizer = cal_optimizer(loss, learning_rate, grad_clip)

In [52]:
targets

<tf.Tensor 'targets:0' shape=(64, 50) dtype=int32>

In [53]:
epochs = 1
# Save every N iterations
save_every_n = 10

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(initial_state)
        loss = 0
        for x, y in generate_batches(embeddings, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed_dict = {inputs: x,
                    targets: y,
                    keep_prob: prob,
                    initial_state: new_state}
            batch_loss, new_state, _ = sess.run([loss, 
                                                 final_state, 
                                                 optimizer], 
                                                 feed_dict = feed_dict)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

TypeError: Fetch argument 0 has invalid type <class 'int'>, must be a string or Tensor. (Can not convert a int into a Tensor or Operation.)

In [32]:
epochs = 1
# Save every N iterations
save_every_n = 10

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(initial_state)
        loss = 0
        for x, y in generate_batches(embeddings, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed_dict = {inputs: x,
                    targets: y,
                    keep_prob: prob,
                    initial_state: new_state}
            batch_loss, new_state, _ = sess.run([loss, 
                                                 final_state, 
                                                 optimizer], 
                                                 feed_dict = feed_dict)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

TypeError: Fetch argument 0 has invalid type <class 'int'>, must be a string or Tensor. (Can not convert a int into a Tensor or Operation.)

In [21]:
tf.train.get_checkpoint_state('checkpoints')

Choosing top n characters for prediction

In [ ]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

Predicting (Sampling) to generate new text

In [ ]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

In [ ]:
tf.train.latest_checkpoint('checkpoints')

In [ ]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 5000, lstm_size, len(vocab), prime="Far")
print(samp)