## CharRNN - Harry Potter

Character wise RNN to generate new text based on Harry Potter Books.

In [1]:
import tensorflow as tf
import numpy as np
import time
from collections import Counter

Load the text file and convert it into integers using dictionaries to convert the characters to and from integers. We will only use the 1st book Harry Potter and Sorcerer's Stone.

In [6]:
text = open('HPBook1.txt', 'r', encoding = 'utf-8')
text = text.read()
print('Some sample text from the book -->')
text[:1000]

Some sample text from the book -->


"Harry Potter and the Sorcerer's Stone \n\nCHAPTER ONE \n\nTHE BOY WHO LIVED \n\nMr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense. \n\nMr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere. \n\nThe Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn't think they could bear it if anyone found out about 

#### Some text analysis

In [7]:
total_words = len(text.split())
total_characters = len(text)
unique_words = len(set(text.split()))
unique_characters = len(set(text))

print ("Total words in book :", total_words)
print ("Total characters in book :", total_characters)
print ("Unique words in book :", unique_words)
print ("Unique characters in book :", unique_characters)

Total words in book : 78449
Total characters in book : 442744
Unique words in book : 11897
Unique characters in book : 80


In [8]:
paragraphs = text.split('\n\n')
print ("Total Paragraphs :", len(paragraphs))

Total Paragraphs : 3033


In [9]:
most_words = Counter()
for i in range(len(paragraphs)):
    for x in paragraphs[i]:
        most_words[x] +=1

In [10]:
most_words.most_common()

[(' ', 78449),
 ('e', 39628),
 ('t', 27993),
 ('a', 25887),
 ('o', 25809),
 ('n', 21337),
 ('r', 20990),
 ('h', 19535),
 ('i', 19422),
 ('s', 18870),
 ('d', 15932),
 ('l', 14385),
 ('u', 9562),
 ('y', 8293),
 ('g', 8127),
 ('w', 7744),
 ('m', 6729),
 ('f', 6431),
 ('c', 6403),
 ('.', 6136),
 (',', 5658),
 ('b', 4980),
 ('p', 4909),
 ('"', 4747),
 ('k', 3930),
 ("'", 3141),
 ('H', 2996),
 ('v', 2716),
 ('-', 1986),
 ('I', 1393),
 ('T', 1055),
 ('S', 844),
 ('?', 754),
 ('A', 703),
 ('D', 685),
 ('M', 665),
 ('R', 660),
 ('W', 653),
 ('P', 639),
 ('G', 492),
 ('N', 488),
 ('!', 474),
 ('F', 426),
 ('x', 381),
 ('B', 348),
 ('O', 332),
 ('Y', 326),
 ('j', 319),
 ('C', 293),
 ('E', 287),
 ('z', 259),
 ('q', 217),
 ('L', 209),
 ('Q', 203),
 ('U', 193),
 ('V', 192),
 (';', 135),
 ('K', 79),
 (':', 69),
 ('J', 51),
 (')', 33),
 ('(', 30),
 ('“', 11),
 ('1', 11),
 ('3', 8),
 ('4', 6),
 ('0', 5),
 ('Z', 5),
 ('9', 4),
 ('7', 4),
 ('2', 3),
 ('X', 2),
 ('*', 2),
 ('5', 2),
 ('6', 1),
 ('8', 1),


In [11]:
set(text)

{'\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '\\',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '~',
 '–',
 '“'}

In [12]:
vocab = sorted(set(text))
vocab_to_int = {c : i for i,c in enumerate(vocab)}
#int_to_vocab = {i : c for i,c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
embeddings = np.array([vocab_to_int[i] for i in text], dtype=np.int32)

In [13]:
vocab_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '?': 23,
 'A': 24,
 'B': 25,
 'C': 26,
 'D': 27,
 'E': 28,
 'F': 29,
 'G': 30,
 'H': 31,
 'I': 32,
 'J': 33,
 'K': 34,
 'L': 35,
 'M': 36,
 'N': 37,
 'O': 38,
 'P': 39,
 'Q': 40,
 'R': 41,
 'S': 42,
 'T': 43,
 'U': 44,
 'V': 45,
 'W': 46,
 'X': 47,
 'Y': 48,
 'Z': 49,
 '\\': 50,
 'a': 51,
 'b': 52,
 'c': 53,
 'd': 54,
 'e': 55,
 'f': 56,
 'g': 57,
 'h': 58,
 'i': 59,
 'j': 60,
 'k': 61,
 'l': 62,
 'm': 63,
 'n': 64,
 'o': 65,
 'p': 66,
 'q': 67,
 'r': 68,
 's': 69,
 't': 70,
 'u': 71,
 'v': 72,
 'w': 73,
 'x': 74,
 'y': 75,
 'z': 76,
 '~': 77,
 '–': 78,
 '“': 79}

In [14]:
print ("Examples encodings (inputs to our NN) -->>")
print (text[:120])
print (embeddings[:120])

Examples encodings (inputs to our NN) -->>
Harry Potter and the Sorcerer's Stone 

CHAPTER ONE 

THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet D
[31 51 68 68 75  1 39 65 70 70 55 68  1 51 64 54  1 70 58 55  1 42 65 68 53
 55 68 55 68  4 69  1 42 70 65 64 55  1  0  0 26 31 24 39 43 28 41  1 38 37
 28  1  0  0 43 31 28  1 25 38 48  1 46 31 38  1 35 32 45 28 27  1  0  0 36
 68 10  1 51 64 54  1 36 68 69 10  1 27 71 68 69 62 55 75  8  1 65 56  1 64
 71 63 52 55 68  1 56 65 71 68  8  1 39 68 59 72 55 70  1 27]


Since we are working with individual characters, it's a classification problem in which we are trying to predict the next character from the previous text. Here's how many 'classes' our network has to pick from.

### Building the Model

Defining placeholders for inputs, targets, learning rate and dropout rate

In [15]:
def placeholders(batch_size, step_size):
    inputs = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='inputs')
    targets = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='targets')
    #lr = tf.placeholder(tf.float32, name='learning_rate')
    keep_prob = tf.placeholder(tf.float32, name= 'prob')
    
    return inputs, targets, keep_prob

Creating LSTM cells for our RNN

In [16]:
def lstms(lstm_size, layers, batch_size, keep_prob):
    
    def build_cell(lstm_size, keep_prob):
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(layers)])
    state = cell.zero_state(batch_size, tf.float32)
    
    return cell, state

Output from RNN

In [17]:
def rnn_output(lstm_output, input_size, output_size):
    sequence = tf.concat(lstm_output, axis=1)
    x = tf.reshape(sequence, [-1, input_size])
    
    with tf.variable_scope('softmax'):
        weights = tf.Variable(tf.truncated_normal(shape=(input_size, output_size), stddev=0.1))
        bias = tf.Variable(tf.zeros(output_size))
        
    logits = tf.matmul(x, weights) + bias
    predictions = tf.nn.softmax(logits, name='predictions')                          
    
    return predictions, logits

Calcualting loss for the network

In [18]:
def losses(logits, y, lstm_size, num_classes):
    labels = tf.reshape(tf.one_hot(y, num_classes), logits.get_shape())
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
    
    return loss

Defining Hyperparameters

In [38]:
batch_size = 128
num_steps = 100        
lstm_size = 512 
num_layers = 2         
learning_rate = 0.001  
prob = 0.5 
grad_clip = 5
num_classes = len(vocab)

Generating batches to feed into NN

In [20]:
def generate_batches(inputs, batch_size, num_steps):
    char_batch = batch_size * num_steps
    num_batches = len(inputs)//char_batch
    
    idx = char_batch * num_batches 
    inputs = inputs[:idx]
    inputs = inputs.reshape((batch_size, -1))
    
    for i in range(0, inputs.shape[1], num_steps):
        x = inputs[:, i : i+num_steps]
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        
        yield x, y

In [21]:
batches = generate_batches(embeddings, 10, 50)
x, y = next(batches)

In [22]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 51 68 68 75  1 39 65 70 70]
 [ 1 69 66 65 61 55  1 51 52 65]
 [70 69  1 52 55 51 61 10  1  0]
 [64 65 69 55 10  1  0  0  3 48]
 [70 58 55 59 68  1 56 51 53 55]
 [56 65 75 69  1 69 64 55 55 68]
 [64 70  1 57 51 59 64 69  1 70]
 [ 1 51 64 65 70 58 55 68  1 68]
 [51 68 54  1 58 59 63  1 51 64]
 [65 62 65 57 75  8  1 31 55 68]]

y
 [[51 68 68 75  1 39 65 70 70 55]
 [69 66 65 61 55  1 51 52 65 71]
 [69  1 52 55 51 61 10  1  0  0]
 [65 69 55 10  1  0  0  3 48 55]
 [58 55 59 68  1 56 51 53 55 69]
 [65 75 69  1 69 64 55 55 68 59]
 [70  1 57 51 59 64 69  1 70 58]
 [51 64 65 70 58 55 68  1 68 55]
 [68 54  1 58 59 63  1 51 64 54]
 [62 65 57 75  8  1 31 55 68 63]]


Optimizer and fixing exploding gradient problem by clipping beyond a threshold

In [23]:
def cal_optimizer(loss, learning_rate, clipping):
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), clipping)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

Setting up all variables and placeholders

In [39]:
tf.reset_default_graph()

## Getting input tensors
inputs, targets, keep_prob = placeholders(batch_size, num_steps)

## Creating LSTM Cell
cell, initial_state = lstms(lstm_size, num_layers, batch_size, keep_prob)

## One hot encode inputs to run the data through RNN layers
one_hot_inputs = tf.one_hot(inputs, num_classes)

## Collect outputs
outputs, state = tf.nn.dynamic_rnn(cell, one_hot_inputs, initial_state = initial_state)
final_state = state

## Predictions and Logits
predictions, logits = rnn_output(outputs, lstm_size, num_classes)

## Getting losses and optimizer(ADAM)
loss = losses(logits, targets, lstm_size, num_classes)
optimizer = cal_optimizer(loss, learning_rate, grad_clip)

### Training the network

In [41]:
epochs = 100
save_every_n = 300

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    counter = 0
    for e in range(epochs):
        new_state = sess.run(initial_state)
        for x, y in generate_batches(embeddings, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed_dict = {inputs: x,
                    targets: y,
                    keep_prob: prob,
                    initial_state: new_state}
            batch_loss, new_state, _ = sess.run([loss, 
                                                 final_state, 
                                                 optimizer], 
                                                 feed_dict = feed_dict)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/100...  Training Step: 1...  Training loss: 4.3825...  0.5479 sec/batch
Epoch: 1/100...  Training Step: 2...  Training loss: 4.2962...  0.4943 sec/batch
Epoch: 1/100...  Training Step: 3...  Training loss: 3.8650...  0.4928 sec/batch
Epoch: 1/100...  Training Step: 4...  Training loss: 5.3728...  0.4937 sec/batch
Epoch: 1/100...  Training Step: 5...  Training loss: 4.2237...  0.4943 sec/batch
Epoch: 1/100...  Training Step: 6...  Training loss: 3.8735...  0.4941 sec/batch
Epoch: 1/100...  Training Step: 7...  Training loss: 3.6982...  0.4940 sec/batch
Epoch: 1/100...  Training Step: 8...  Training loss: 3.5618...  0.4931 sec/batch
Epoch: 1/100...  Training Step: 9...  Training loss: 3.4899...  0.4932 sec/batch
Epoch: 1/100...  Training Step: 10...  Training loss: 3.4777...  0.4929 sec/batch
Epoch: 1/100...  Training Step: 11...  Training loss: 3.4496...  0.4926 sec/batch
Epoch: 1/100...  Training Step: 12...  Training loss: 3.4204...  0.4936 sec/batch
Epoch: 1/100...  Training

In [42]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i3400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i300_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i900_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1500_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2100_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2700_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3300_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3400_l512.ckpt"

Choosing top n characters for prediction

In [43]:
def select_characters(predictions, vocab_size, top = 5):
    probs = np.squeeze(predictions)
    probs[np.argsort(probs)[: -top]] = 0
    probs = probs / np.sum(probs)
    chars = np.random.choice(vocab_size, 1, p=probs)[0]
    return chars

Predicting (Sampling) to generate new text

In [44]:
def sample_and_select(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime] 
    
    # During sampling and selecting, we pass  one character at a time
    batch_size, num_steps = 1, 1
    num_layers = 2
    num_classes = len(vocab)
    learning_rate = 0.001  
    grad_clip = 5
    
    tf.reset_default_graph()

    ## Getting input tensors
    inputs, targets, keep_prob = placeholders(batch_size, num_steps)

    ## Creating LSTM Cell
    cell, initial_state = lstms(lstm_size, num_layers, batch_size, keep_prob)

    ## One hot encode inputs to run the data through RNN layers
    one_hot_inputs = tf.one_hot(inputs, num_classes)

    ## Collect outputs
    outputs, state = tf.nn.dynamic_rnn(cell, one_hot_inputs, initial_state = initial_state)
    final_state = state

    ## Predictions and Logits
    prediction, logits = rnn_output(outputs, lstm_size, num_classes)

    ## Getting losses and optimizer(ADAM)
    loss = losses(logits, targets, lstm_size, num_classes)
    optimizer = cal_optimizer(loss, learning_rate, grad_clip)

    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(initial_state)
        
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {inputs: x,
                    keep_prob: 1.,
                    initial_state: new_state}
            preds, new_state = sess.run([prediction, final_state], 
                                         feed_dict=feed)

        c = select_characters(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {inputs: x,
                    keep_prob: 1.,
                    initial_state: new_state}
            preds, new_state = sess.run([prediction, final_state], 
                                         feed_dict=feed)

            c = select_characters(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

In [45]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i3400_l512.ckpt'

In [47]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime='It was a ')
print(samp)

It was a few weeks to be troll on the third floor. He was starting to return the cloak on the fire. The small reached a parser, a hore, but before Filch spat and say inside. 

"There's a note -- shot yeh to go?" 

Harry and Ron with a bag in the tirle's back by anyence. 

And thene, the boy mad his newspaper by his suddenly hurs, all sorrd, the studing wind smiled. 

"I heard it -- look --" 

"You could have mind her to do anyone else -- the counter stray him by a classroom. He had been pressed on anything." 

Harry saw the deak shoppes. 

"Should have been being in the arrsadd to speed to tall him in front." 

"What about that, I'll guarding you." 

A letter with the back in the corred of Harry's but bot of second, which was still glasing at him, and a whispered. 

Harry thought this was standing around instead, of course, the best greated was was moved to sel him from by here. He was looking at his seem. Harry had sand, "It wouldn't know what to do with the Dursleys, he said, He had 

In [51]:
checkpoint = 'checkpoints/i2700_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

It was a few leaver that. 

"You drink on the train? I've never get it." 

"Give me a loud, I'm not try only going?" 

"Yes," said Ron. 

"I say he's got how to ktop yer late?" Hagrid said, "Shaghim," Harry said. 

"You've been sayin' an owd?" He gaspping at the stander book. 

"He's lott his protecting to do with you, that same yes?" 

"Wonder, I'm going to do you than?" 

"What happen't this in the moment," he began to think twere any most moment as this start something lestens bowe was a surprise to but Hermione Granger had sighe. The seat had started and still himself into his cloak, but he was take the boy was a few seconds and still had a boit of stratgers with the gable. Hagrid gave a second later, but harry thought he had gone on the still. 

"Yes,, he's a shapp pick to get hurryed up the corner of them, who don't something to go to Harry." 

"Why were to something," said Harry. "Yeh, we're not seen that the points he's going to be an ord." 

He looked looking at another tood t

In [50]:
checkpoint = 'checkpoints/i1500_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

It was the teachers whe wan to be about to trind to see the flating out of a start for a more to see it to bit on Harry his head, but Harry. Hagrid sweeped to his fant. He'd then wouldn't be allare that was a standed for andone they had that the troll stumbned. 

"Hagrid!" she was said that they started, something about the the stand of his brink. Harry whispered to him forthed. He was seeming to be to trist the trush and shilly started to straight her that they went onto the conntry her take, and Harry was a boitt boy of his bright, ship han than his fingers of them was she stick, harring him as the big on the start of the cat on the firelots shaded as the boy was shating his found, but Hermione were sayed. 

"See?" he said. "I don't trought heard to be in the cold the fores --" 

Harry. Hagrid was soired, and there was stunding to the chowe to the both she and his later to the sturing with Hagrid the seat of they crunk and told him when they shived as he was a bit of a boy a bit on t

In [49]:
checkpoint = 'checkpoints/i300_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

It was sall ald ond at he was tin with sitk and worly were thourle to bet the thoud, the wis to tout on was salle thim has sor to tout he ald thering sat sing an wished tithed, but how his tored. 

Ant to tand war sherise tere win her tally thand thing, tore and." 

"Harry he sould of thine. Ther whas stin ghe pilking what ard and whe he and thene to bere ther hing. "Was ha the tho chas hind and the pasteren. I wal an the thit wardes was ane har wored tome bothed him aredes there sit tones was ha the pelined touther an what and and wat tite ha corle aldering sours to than simested and. 

"Wat war had seedile stoung of hith he tore the thand allent wim stat inght. 

"Yus tat ant his, steing, ber at ass ot wint," seis as ind the tol ander tom har stoud be ald has inged and thing ald and wast the card an hourd wont the tha tas. 

"They and an the wort he the pat them the sallist, has at whast at at at withe tor. I wath wall see hem. Hearr the thint the chis and to the had thene hed hing h